import { Class808 } from 'Class808.js';
export var Class809 = function () {
    var b = {};
    var a = new Array(25);
    b.member10533 = a;
    a[0] = Class808({ name: false ? {} : 'Defaults' });
    a[1] = Class808({ name: false ? {} : 'Jaclib' });
    a[2] = Class808({ name: false ? {} : 'Jaggl' });
    a[3] = Class808({ name: false ? {} : 'Jagdx' });
    a[4] = Class808({ name: false ? {} : 'Sw3d' });
    a[5] = Class808({ name: false ? {} : 'Hw3d' });
    a[6] = Class808({ name: false ? {} : 'Shaders' });
    a[7] = Class808({ name: false ? {} : 'Materials' });
    a[8] = Class808({ name: false ? {} : 'Config' });
    a[9] = Class808({ name: false ? {} : 'ConfigLoc' });
    a[10] = Class808({ name: false ? {} : 'ConfigEnum' });
    a[11] = Class808({ name: false ? {} : 'ConfigNPC' });
    a[12] = Class808({ name: false ? {} : 'ConfigObj' });
    a[13] = Class808({ name: false ? {} : 'ConfigSeq' });
    a[14] = Class808({ name: false ? {} : 'ConfigSpot' });
    a[15] = Class808({ name: false ? {} : 'ConfigStruct' });
    a[16] = Class808({ name: false ? {} : 'Quickchat' });
    a[17] = Class808({ name: false ? {} : 'QuickchatGlobal' });
    a[18] = Class808({ name: false ? {} : 'Particles' });
    a[19] = Class808({ name: false ? {} : 'Billboards' });
    a[20] = Class808({ name: false ? {} : 'Huffman' });
    a[21] = Class808({ name: false ? {} : 'Interfaces' });
    a[22] = Class808({ name: false ? {} : 'Clientscripts' });
    a[23] = Class808({ name: false ? {} : 'FontMetrics' });
    a[24] = Class808({ name: false ? {} : 'WorldmapData' });
    return b;
}();